### PR TITLE
Migration to netcore

### PR DESCRIPTION
**Pull request by OlegZee**
This PR is not for merging (as the work is incomplete) but just to clarify some details.

What is done:

* new project files with netstandard target
* replaced invokations of powerpack's Compile with fsharp.quotations.evaluator and added stubs to avoid commenting out code
* replaced FsPickler with MessagePack (though I do not know its capabilities)
* migrated paket.template to fsproj properties for Akkling.TestKit project
* as FSI is not available I added examples-app project with just a single sample copied. Just to check it works

Here're the tasks, ideas and questions:

* fsppickler -> MessagePack: is it worth testing the last one or wait, or use conditional compilation for NETSTANDARD
* quotations evaluator: wait or conditional compilation
* projects cleanup
* tests do not work, it complains about missing hostpolicy.dll
* use "dotnet pack" for making nuget packages (internally it will use paket), just less data files and less duplication
* there's a mess with netstandard2.0: some library triggers Microsoft.Extensions.Logging 2.0.0 dependency which requires netstandard 2.0. So I removed `framework` from paket.dependencies just to get all deps resolved

### CODE REVIEW

**Comment by Horusiath** [comment]
Would you mind to rebase your branch?

**Comment by OlegZee** [comment]
Merged (not to restart PR).

**Comment by object** [comment]
Thrilled to see support for .NET Core. What are the next steps? And which NET Standard version is it intended to support?

**Comment by OlegZee** [comment]
@object I hope it will support netstandard 1.6. This obstacle I mentioned must be somehow resolved. Next 
"big" thing is to check if MessagePack is ok.

I sometimes feel I haven't got enough experience in netcore troubleshooting so such issues like tests which are not starting, or this dependency mess take so much time.

**Comment by Horusiath** [comment]
Before I merge this one I need to create some more detailed tests and establish CI. I'm afraid, this PR will break some things:

1. Replacing FsPickler with MsgPack is no go - FsPickler is used for serializing F# quotation expressions. It could be potentially fully replaced by Hyperion, which also has this feature, but I don't know if it's complete (there are many potential expressions that have not been tested).
2. I'm not sure about the current state of Quotations evaluator either, but this probably is a less of an issue.

**Comment by ForNeVeR** [comment]
@Horusiath 

>  I need to [...] establish CI.

If you need any help, I have small experience in setting up the F# CI on .NET Core. Take a look at [Nightwatch](https://github.com/ForNeVeR/Nightwatch) or [Emulsion](https://github.com/codingteam/emulsion) (the CI setup is basically the same) and/or ping me in any PR / issue / directly in Telegram (you guys know my id).

I'm ready and willing to help with that.

**Comment by object** [comment]
Now that FsPickler supports .NET Standard, does support for .NET Core look more realistic, or FsPickler will be replaced with Hyperion?

**Comment by vasily-kirichenko** [comment]
@object see https://github.com/Horusiath/Akkling/pull/92, FsPickler has gone.

**Comment by Horusiath** [comment]
I'll close this. Project has been moved to support .NET Standard with as minimal set of breaking changes as possible. Version 0.9 is now live.

**Pull request closed without merging**
