### PR TITLE
Add Hocon CE

### PR DESCRIPTION
**Pull request by Shmew**
This PR adds computation expressions for the full (or at least what I could find, there isn't exactly a schema laying around as far as I could find) set of configuration options for Akka.NET. In addition to type safety (and UoM) and some minor niceties, it also performs checks against valid ranges (such as if a field can only be positive, or a power of two, etc).

I couldn't find a great way to test the CE in-depth, as `Config` doesn't support equality in a way that would help with this, although eye-balling it looks almost identical.

### CODE REVIEW

**Comment by Horusiath** [comment]
This is huge piece of work! I'll need a while to take a look at it. A thing I think, we could take advantage of is using `typeof<>` instead of providing strings with FQTN. But nonetheless, this is something that can be improved gradually before releasing.

**Comment by Shmew** [comment]
> A thing I think, we could take advantage of is using typeof<> instead of providing strings with FQTN.

Yeah I wasn't quite sure what the exact rules around that is so just left it as a string for now. I'm pretty satisfied with it so far, but the biggest issue is it conflicts with the `actor` CE in the library proper. I don't think config files would be used all that often in the same files as actors in actual use, but would appreciate your input.

**Comment by Swoorup** [comment]
Wondering if this does support like merging configs?

**Comment by Shmew** [comment]
I wanted to be able to better merge configs, but I couldn't find any good way to accomplish it as the `Config` fallback method doesn't even do it very well.

**Comment by Yakimych** [comment]
@Horusiath @Shmew 
This looks fantastic! Is there a way to use this at this time? I can't seem to find `Akka.Hocon` on Nuget 😕

**Pull request merged**
